### ISSUE TITLE
Enhancment

### ISSUE THREAD

**Issue by HasanAbbadi** [Pauloo27/gotroller#1]
hey there,
when there is a song playing the whole name of the song shows, which is really annoying.
cause it pushes other modules away and i cant see nor use them.

if there is a way to make it show like two words then dots ex. "I'm running....", that would be super nice.
thx
![2021-04-12_10-23](https://user-images.githubusercontent.com/78548167/114356384-335ccd00-9b79-11eb-9759-859b83d60c63.png)

**Comment by pauloo27** [comment]
I've just added a feature to limit it's size... Can you test it?

Don't forget to git pull and rebuild first.
https://github.com/Pauloo27/gotroller#config

**Comment by HasanAbbadi** [comment]
sorry for replying late, i was busy.
i just tried it out and it works perfectly thanks a lot :)
